### ISSUE TITLE
Template has changed to make some parameters non-optional

### ISSUE THREAD

**Issue by jan-smartward** [theonestack/hl-component-ecs-service#45]
`/data/out/cfndsl/ecs-service.compiled.cfndsl.rb:442:in `block (2 levels) in eval_file_with_extras': undefined method `empty?' for 0:Integer (NoMethodError)`

In this case this is referencing
```HealthCheckGracePeriodSeconds health_check_grace_period unless health_check_grace_period.empty?```
but there are several other similar changes where `if defined?` gets changed to `empty?` which doesn't work if the variable is not defined. 

Change comes from: https://github.com/theonestack/hl-component-ecs-service/commit/07768f7f24c1508d22264e663aa9a269a9cc9f10

@Samseppiol @Guslington

**Comment by Samseppiol** [comment]
fixed in https://github.com/theonestack/hl-component-ecs-service/pull/46

**Comment by Guslington** [comment]
Released in `2.7.1`
https://github.com/theonestack/hl-component-ecs-service/releases/tag/2.7.1
